### PR TITLE
parallelise image drawing

### PR DESCRIPTION
**Pull request by melsman**
There seems to be a problem on my machine with this PR, but Troels is suggesting that I create the PR so that other people can try it out. To adjust the parallelisation, one can alter the definitions of `G` (grid size) and `n_tries` in shapegen.fut.

### CODE REVIEW

**Comment by melsman** [comment]
Even with simpler triangle calculations, my laptop produces weird results when trying to render a dog.

After about 30 seconds, the rendering is not improving:

image

The GPU is working though, but it seems the indexes that are computed are erroneous...

**Comment by athas** [comment]
The stall was due to a bug in the `cpprandom` library, which I have just fixed in a new version.

**Comment by melsman** [comment]
... We are now initiating the rng at each iteration from count and the initial seed... This change allow us to eliminate some joins...

**Comment by melsman** [comment]
Everything works well now!

**Comment by nqpz** [comment]
This is great!

I might make a non-interactive interface to this, now that it's fast enough to end up in a reasonable approximation pretty quickly.

**Pull request merged**
